services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tierone-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    depends_on:
      - mysql
      - redis
    networks:
      - tierone-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - REDIS_HOST=redis

  mysql:
    image: mysql:8.0
    container_name: tierone-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tierone_orders
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: tierone_user
      MYSQL_PASSWORD: tierone_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tierone-network
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: tierone-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tierone-network
    command: redis-server --appendonly yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tierone-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - tierone-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  tierone-network:
    driver: bridge
